import { useState, type FormEvent } from 'react';
import { BellRing, CheckCircle2, Send, ShieldCheck, UsersRound } from 'lucide-react';
import { Button } from '@/components/common/Button';
import { PageHeader } from '@/components/common/PageHeader';
import { useSendNotification } from '@/hooks/useCommunications';

export function NotificationsPage() {
  const send = useSendNotification(); const [delivered, setDelivered] = useState<number | null>(null);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const v = Object.fromEntries(new FormData(event.currentTarget)); send.mutate({ userId: String(v.userId || '') || undefined, type: String(v.type) as 'SYSTEM', title: String(v.title), message: String(v.message), actionUrl: String(v.actionUrl || '') || undefined }, { onSuccess: (result) => setDelivered(result.delivered) }); };
  return <div className="page-stack"><PageHeader eyebrow="Communications" title="Notification center" description="Send a targeted alert or broadcast to every active Fantasy Ethiopia manager."/>
    <div className="split-layout"><form className="glass-card premium-form form-panel" onSubmit={submit}><div className="panel-heading"><div className="card-icon purple"><BellRing/></div><div><h2>Compose notification</h2><p>Delivery uses the existing in-app notification channel.</p></div></div><label>Audience<select name="audience" defaultValue="all"><option value="all">All active users</option><option value="target">One specific user</option></select></label><label>Target user ID <span>(optional)</span><input name="userId" placeholder="Leave blank for platform-wide broadcast"/></label><label>Notification type<select name="type" defaultValue="SYSTEM"><option>SYSTEM</option><option>DEADLINE</option><option>WALLET</option><option>LEAGUE</option><option>WINNER</option></select></label><label>Title<input name="title" required maxLength={120}/></label><label>Message<textarea name="message" required rows={6} maxLength={2000}/></label><label>Action URL <span>(optional)</span><input name="actionUrl" placeholder="/wallet or https://…"/></label><Button type="submit" isLoading={send.isPending} fullWidth><Send className="h-4 w-4"/>Send notification</Button>{send.isError ? <p className="form-error">Notification could not be delivered.</p> : null}{delivered !== null ? <p className="form-success"><CheckCircle2/>Delivered to {delivered.toLocaleString()} user{delivered === 1 ? '' : 's'}.</p> : null}</form>
      <aside className="space-y-4"><div className="glass-card info-panel"><UsersRound/><h2>Audience control</h2><p>A blank user ID broadcasts only to active accounts. Add a user ID for a single-recipient delivery.</p></div><div className="glass-card info-panel"><ShieldCheck/><h2>Safe delivery</h2><p>This interface does not introduce new channels, jobs, or backend behavior.</p></div></aside></div></div>;
}
